package helloworld;

/*
 * EXCEPTION

Nếu try - catch không handle được 1 exception nào đó, thì khối lệnh trong finally vẫn sẽ chạy, sau đó mới throw exception đó

throws: at the method definition => to warn its caller
throw: in method body

When overriding, method of subclass cannot throw any new exception.
 */

public class HelloException {
    
}
